---
title: "A map with Leaflet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Created on `r format(Sys.Date(), "%d %B %Y")`

```{r libs, include=FALSE}
library(tidyverse)
library(leaflet)
library(WikidataQueryServiceR)

```

```{r data}
# query football stadium data
query <-
  'SELECT ?club ?clubLabel ?venue ?venueLabel ?coordinates\nWHERE\n{\n	?club wdt:P31 wd:Q476028 .\n	?club wdt:P115 ?venue .\n	?venue wdt:P625 ?coordinates .\n	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }\n}'

#df <- query_wikidata(query, format = "smart")
df <- read_rds("df.RData")

df <- df %>% 
  select(-club, -venue) %>% 
  mutate(coordinates = str_remove_all(coordinates, "Point\\(|\\)")) %>% 
  separate(coordinates, into = c("lng", "lat"), sep = " ") %>% 
  mutate_at(vars(lat, lng), as.numeric)

```


```{r map}

# randomly select n stadiums
df2 <- sample_n(df, 100)


# create an icon to place footballs at locations of football stadiums
football_icon <- makeIcon(
  iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Soccerball.svg/240px-Soccerball.svg.png",
  iconWidth = 21, iconHeight = 21,
  iconAnchorX = 11, iconAnchorY = 11
)


``` 

## Locations of randomly selected football stadiums

Click on a football (or a cluster) to zoom in.

```{r}

df2 %>% 
  mutate(label = map2(venueLabel, 
                      clubLabel, 
                      ~htmltools::HTML(sprintf("<b>%s</b><br>Home of %s", .x, .y)))) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat = ~lat, 
             lng = ~lng, 
             label = ~label, 
             icon = football_icon,
             clusterOptions = markerClusterOptions()) %>% 
  leaflet.extras::addResetMapButton()

```

